# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-07-29 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_list', '0002_auto_20160729_1326'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dreamreal',
            table='dreamreal',
        ),
        migrations.AlterModelTable(
            name='online',
            table='online',
        ),
    ]
